@startuml

participant Alice
participant Bob

Alice -> Bob : Hello Bob, how are you?
activate Alice
activate Bob

alt is sick
    Bob --> Alice : Not so good :(
else is well
    Bob --> Alice : Feeling fresh like a daisy
end

opt Extra response
    Bob --> Alice : Thanks for asking
end

deactivate Bob
deactivate Alice

@enduml